### ISSUE TITLE
initialised_

### ISSUE THREAD

**Issue by calvinmetcalf** [crypto-browserify/hash-base#1]
[dangling underscores](https://github.com/crypto-browserify/hash-base/blob/b10031234ba760da754b2f8fa3a4c20d76336e5b/index.js#L7) are not really our style, we tend to put them at the beginning, also that variable should probably be _notInitialized

**Comment by fanatid** [comment]
yea, agree, just take this name from [node crypto](https://github.com/nodejs/node/blob/c60faf6ba85b6365145fd8215ed572efa9f25fdc/src/node_crypto.cc#L3678)
I'll change

**Comment by fanatid** [comment]
Renamed to `_initialized` in https://github.com/crypto-browserify/hash-base/commit/6e458c69f9cf124758f68a01a8232fc7c3269945

**Comment by calvinmetcalf** [comment]
the name is also extremely confusing because it's more about preventing
digest from being called twice

**Comment by fanatid** [comment]
any other better name? error message also isn't good, but we can't change because this message in node crypto and because this I think that we should use name `_initialized`..

**Comment by calvinmetcalf** [comment]
the error name is lame, we can't change that, but since the check is actually preventing us from calling digest twice change the variable to something like _finalized and add a comment that the error is due to api compatablility

**Comment by fanatid** [comment]
I liked `_finalized`, may be we also should make PR to node?

**Comment by calvinmetcalf** [comment]
in progress

**Comment by fanatid** [comment]
nice! are you want change variable name and error message?

**Comment by calvinmetcalf** [comment]
just variable name for now

**Comment by fanatid** [comment]
why not message also? because it will make chaos with message in different node versions?

**Comment by calvinmetcalf** [comment]
because it might not be accepted and if it is the message might change
